var json_Q22022_9 = {
"type": "FeatureCollection",
"name": "Q22022_9",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "864 Eagle Dr", "CITY": "Four Seasons", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65049.0, "PRICE": 2775000.0, "BEDS": 6.0, "BATHS": 7.0, "LOCATION": "Palisades Point #5", "SQUARE FEET": 7610.0, "LOT SIZE": 45302.0, "YEAR BUILT": null, "DAYS ON MARKET": 344.0, "$/SQUARE FEET": 365.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Four-Seasons/864-Eagle-Dr-65049/home/78093693", "SOURCE": "LOBR", "MLS": "3546164" }, "geometry": { "type": "Point", "coordinates": [ -92.7239061, 38.1846044 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "216 Bello Point Dr", "CITY": "Sunrise Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65079.0, "PRICE": 925000.0, "BEDS": 4.0, "BATHS": 3.5, "LOCATION": "Heritage Isle #8", "SQUARE FEET": 3262.0, "LOT SIZE": null, "YEAR BUILT": null, "DAYS ON MARKET": 1.0, "$/SQUARE FEET": 284.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Sunrise-Beach/216-Bello-Point-Dr-65079/home/77898992", "SOURCE": "LOBR", "MLS": "3553830" }, "geometry": { "type": "Point", "coordinates": [ -92.640526, 38.174756 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Condo/Co-op", "ADDRESS": "821 Winn Rd", "CITY": "Osage Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65065.0, "PRICE": 409000.0, "BEDS": 3.0, "BATHS": 2.0, "LOCATION": "Kapilana Estates", "SQUARE FEET": 1601.0, "LOT SIZE": null, "YEAR BUILT": null, "DAYS ON MARKET": 4.0, "$/SQUARE FEET": 255.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Osage-Beach/821-Winn-Rd-65065/home/78120727", "SOURCE": "LOBR", "MLS": "3553773" }, "geometry": { "type": "Point", "coordinates": [ -92.6485148, 38.1247926 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "100 Summer Pt", "CITY": "Sunrise Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65079.0, "PRICE": 575900.0, "BEDS": 3.0, "BATHS": 3.0, "LOCATION": "Summer Point", "SQUARE FEET": 1880.0, "LOT SIZE": 3049.0, "YEAR BUILT": null, "DAYS ON MARKET": 6.0, "$/SQUARE FEET": 306.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Sunrise-Beach/100-Summer-Pt-65079/home/185705848", "SOURCE": "LOBR", "MLS": "3553782" }, "geometry": { "type": "Point", "coordinates": [ -92.7653997, 38.1841943 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "440 Moongate Dr", "CITY": "Osage Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65065.0, "PRICE": 700000.0, "BEDS": 3.0, "BATHS": 3.5, "LOCATION": "Tan-Tar-A Estates", "SQUARE FEET": 3488.0, "LOT SIZE": 8276.0, "YEAR BUILT": null, "DAYS ON MARKET": 6.0, "$/SQUARE FEET": 201.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Osage-Beach/440-Moongate-Dr-65065/home/78113025", "SOURCE": "LOBR", "MLS": "3553517" }, "geometry": { "type": "Point", "coordinates": [ -92.7290544, 38.1347339 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "6572 Robyn Pt", "CITY": "Osage Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65065.0, "PRICE": 1995000.0, "BEDS": 4.0, "BATHS": 4.5, "LOCATION": "Robyn Point", "SQUARE FEET": 3730.0, "LOT SIZE": null, "YEAR BUILT": null, "DAYS ON MARKET": 6.0, "$/SQUARE FEET": 535.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Osage-Beach/6572-Robyn-Pt-65065/home/78138358", "SOURCE": "LOBR", "MLS": "3553751" }, "geometry": { "type": "Point", "coordinates": [ -92.7078433, 38.0996962 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "46 Raven Rd", "CITY": "Eldon", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65026.0, "PRICE": 850000.0, "BEDS": 4.0, "BATHS": 3.0, "LOCATION": "Fischers", "SQUARE FEET": 3706.0, "LOT SIZE": 9148.0, "YEAR BUILT": null, "DAYS ON MARKET": 8.0, "$/SQUARE FEET": 229.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": "June-17-2023 11:00 AM", "NEXT OPEN HOUSE END TIME": "June-17-2023 02:00 PM", "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Eldon/46-Raven-Rd-65026/home/77900326", "SOURCE": "LOBR", "MLS": "3553353" }, "geometry": { "type": "Point", "coordinates": [ -92.6757535, 38.2292235 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "462 Heart Lane Pt", "CITY": "Linn Creek", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65052.0, "PRICE": 1750000.0, "BEDS": 4.0, "BATHS": 3.5, "LOCATION": null, "SQUARE FEET": 3600.0, "LOT SIZE": 15682.0, "YEAR BUILT": null, "DAYS ON MARKET": 8.0, "$/SQUARE FEET": 486.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Linn-Creek/462-Heart-Lane-Pt-65052/home/185675738", "SOURCE": "LOBR", "MLS": "3553687" }, "geometry": { "type": "Point", "coordinates": [ -92.7185751, 38.0988935 ] } }
]
}
