var json_Q42022_11 = {
"type": "FeatureCollection",
"name": "Q42022_11",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "1344 Triple Cove Ln", "CITY": "Climax Springs", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65324.0, "PRICE": 489900.0, "BEDS": 3.0, "BATHS": 2.0, "LOCATION": "Coffman Bend", "SQUARE FEET": 2017.0, "LOT SIZE": 78408.0, "YEAR BUILT": null, "DAYS ON MARKET": 244.0, "$/SQUARE FEET": 243.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Climax-Springs/1344-Triple-Cove-Ln-65324/home/78094091", "SOURCE": "LOBR", "MLS": "3548965" }, "geometry": { "type": "Point", "coordinates": [ -92.9563698, 38.2061379 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "25385 Flat Car Dr", "CITY": "Warsaw", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65355.0, "PRICE": 539000.0, "BEDS": 3.0, "BATHS": 2.0, "LOCATION": "See S, T, R", "SQUARE FEET": 1820.0, "LOT SIZE": 87120.0, "YEAR BUILT": 1995.0, "DAYS ON MARKET": 234.0, "$/SQUARE FEET": 296.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Warsaw/25385-Flat-Car-Dr-65355/home/77940357", "SOURCE": "WCAR", "MLS": "93478" }, "geometry": { "type": "Point", "coordinates": [ -93.238016, 38.2818479 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "191 Stonebridge Ln", "CITY": "Sunrise Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65079.0, "PRICE": 3499900.0, "BEDS": 6.0, "BATHS": 7.0, "LOCATION": "The Villages At Shawnee Bend", "SQUARE FEET": 8060.0, "LOT SIZE": 37462.0, "YEAR BUILT": null, "DAYS ON MARKET": 231.0, "$/SQUARE FEET": 434.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Sunrise-Beach/191-Stonebridge-Ln-65079/home/78112621", "SOURCE": "LOBR", "MLS": "3549143" }, "geometry": { "type": "Point", "coordinates": [ -92.6795573, 38.1534611 ] } },
{ "type": "Feature", "properties": { "SALE TYPE": "MLS Listing", "SOLD DATE": null, "PROPERTY TYPE": "Single Family Residential", "ADDRESS": "974 Brookhaven Ln", "CITY": "Sunrise Beach", "STATE OR PROVINCE": "MO", "ZIP OR POSTAL CODE": 65079.0, "PRICE": 3400000.0, "BEDS": 4.0, "BATHS": 4.5, "LOCATION": "The Villages At Shawnee Bend", "SQUARE FEET": 5070.0, "LOT SIZE": null, "YEAR BUILT": null, "DAYS ON MARKET": 191.0, "$/SQUARE FEET": 671.0, "HOA/MONTH": null, "STATUS": "Active", "NEXT OPEN HOUSE START TIME": null, "NEXT OPEN HOUSE END TIME": null, "URL (SEE https://www.redfin.com/buy-a-home/comparative-market-analysis FOR INFO ON PRICING)": "https://www.redfin.com/MO/Sunrise-Beach/974-Brookhaven-Ln-65079/home/78135338", "SOURCE": "LOBR", "MLS": "3549742" }, "geometry": { "type": "Point", "coordinates": [ -92.6703976, 38.1503696 ] } }
]
}
